#!/usr/bin/env python2.4

import os, sys, codecs
import plasTeX
from plasTeX.TeX import TeX
from plasTeX.Config import config

inencoding = config['encoding']['input']
outencoding = config['encoding']['output']

print >>sys.stderr, 'plasTeX version 1.0'
file = sys.argv[1]
basename = os.path.splitext(file)[0]

# Parse document
s = TeX(codecs.open(file,'r',inencoding))
document = s.parse()

# Write expanded source file
sourcefile = '%s.source' % basename
codecs.open(sourcefile,'w',outencoding).write(document.source)

# Write XML dump
outfile = '%s.xml' % basename
codecs.open(outfile,'w',outencoding).write(document.toXML())

# Apply renderer
from plasTeX.renderers.xhtml import xhtml as renderer
renderer.render(document)
